"""add mobile

Revision ID: 623624bc9f00
Revises: 
Create Date: 2019-10-10 21:16:41.158552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623624bc9f00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fb_author', sa.Column('mobile', sa.String(length=12), nullable=True))
    op.create_unique_constraint(None, 'fb_author', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fb_author', type_='unique')
    op.drop_column('fb_author', 'mobile')
    # ### end Alembic commands ###
